env: dev 
urlroot: http://nomads.ncep.noaa.gov/cgi-bin/filter_wave.pl
log_file: log/forecast_downloader.log
log_level: DEBUG
wgrib2_path: /usr/bin
wgrib2_name: wgrib2
db:
        dev:  mysql://forecast:f0r3c4stdb@localhost/forecasts
        test: sqlite://gribdata-test.db
        prod: sqlite://gribdata-prod.db
db_log_file: STDOUT
