env: test
urlroot: http://nomads.ncep.noaa.gov/cgi-bin/filter_wave.pl
log_file: STDOUT
log_level: DEBUG
wgrib2_path: /usr/bin
wgrib2_name: wgrib2
db:
        dev: sqlite://gribdata.db 
        test: sqlite://gribdata-test.db
        prod: sqlite://gribdata-prod.db

    
